### ISSUE TITLE
Feedback on page MigrationGuide

### ISSUE THREAD

**Issue by TristanWellman** [libsdl-org/sdlwiki#129]
There is nothing about SDL_GetVideoSurface in the migration guid. why?

**Comment by icculus** [comment]
Because it's almost always the incorrect thing to use.

The migration guide pushes rendering onto the GPU, even if it's just to get the final results of a software-rendered buffer into the screen, because there are a lot of benefits to that.

**Comment by icculus** [comment]
I thought this was about SDL_GetWindowSurface, sorry. But the point still stands: it doesn't cover it because it encourages you to get away from SDL_Surface.

If you need the "screen" surface previously created, store it in a global variable. More or less, that's all SDL 1.2's SDL_GetVideoSurface is doing.
