### ISSUE TITLE
Garbage text on SDL_Keycode wiki page

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdlwiki#26]
(Transferred from https://github.com/icculus/ghwikipp/issues/27 ...)

On the wiki page for [SDL_Keycode](https://wiki.libsdl.org/SDL_Keycode), this text is present:

![image](https://user-images.githubusercontent.com/35299276/114280602-0806a080-9a08-11eb-9104-55d74f30942f.png)

I assume this text was meant to be replaced/filled in via an automated script.

**Comment by FtZPetruska** [comment]
Hi,
Bumping this up because, I'd like to update some pages on the wiki but I'm not sure about what to do with this kind of text.
Most pages linked in `APIByCategory` will have text such as `<<FullSearchCached(....)>>` under each section, and a list of all function/enum/struct at the bottom. Similarly, some code examples have `<<Include(...)>>` referring to examples on other pages.

My question is: is this text safe to be replaced manually by what should be in place ?

Thanks in advance!

**Comment by icculus** [comment]
This is fixed; the wikiheaders script manages this page now. (Category pages are getting fixed separately though.)
