### ISSUE TITLE
Feedback on page SDL2/README/cmake

### ISSUE THREAD

**Issue by simonrapaka** [libsdl-org/sdlwiki#368]
If you're using a mingw compiler on windows you won't get console output with this config.

To enable it go to `..compilerdir\lib\cmake\SDL2`  and alter the sdl2-config.cmake file 
![image](https://user-images.githubusercontent.com/117975075/232763616-fda3905c-2683-49e3-9a48-e888bcc29a2f.png)

remove the `-mwindows` flag and console output will be enabled

**Comment by icculus** [comment]
@madebr Should we make this a cmake option, or just document this in the README?

**Comment by madebr** [comment]
The issue is with the autotools' generated `sdl2-config.cmake`.
There, the `-mwindows` is kept because it has always been the case in SDL2.
The SDL2 CMake build script however does not add `-mwindows` to the installed SDL2 config files. So there's a discrepancy between autotools and CMake there.
SDL2 `sdl2.pc` adds `-mwindows`.

For SDL3, `-windows` is only added by `sdl3.pc`.
(see https://github.com/libsdl-org/SDL/issues/5948)

Here, let's add an option to the installed `sdl2-config.cmake` script that will optionally drop the `-mwindows`.

```cmake
# Set SDL2_NO_MWINDOWS to a true-ish value to not add the -mwindows link option
if(SDL2_NO_MWINDOWS)
  list(REMOVE_ITEM _sdl2_libraries "-mwindows")
endif()
```
The option will not be present on CMake SDL2 prefixes. (It has the `ON` behavior there)

**Comment by madebr** [comment]
https://github.com/libsdl-org/sdlwiki/pull/370

**Comment by icculus** [comment]
Okay, we have a way to turn things off, and clear documentation on how to do it, I think we're good here. Thanks for jumping on this so quickly, @madebr!
