### ISSUE TITLE
Include the header file in which a function is located in the documentation.

### ISSUE THREAD

**Issue by duerdak** [libsdl-org/sdlwiki#484]
As a quality of life improvement I suggest adding the header file a function is declared in in the documentation. As an example you can check the std::vector docs on [cppreference](https://en.cppreference.com/w/cpp/container/vector) or [cplusplus](https://cplusplus.com/reference/vector/vector/).
So as an SDL example let's say there's a SDL_GenerateVertexBuffer function in a fictional buffers.h, at the top of the function docs page it would say "Defined in < buffers >".

**Comment by icculus** [comment]
Ooh, I like this idea.

**Comment by icculus** [comment]
This just landed and is live on the wiki!

Like on this random page:

https://wiki.libsdl.org/SDL3/SDL_GetWindowProperties

This will also add the information to generated manpages (but obviously not the headers, since you'd be reading that file at the time).

I need to update the other projects, like SDL_mixer, but if you all like this, that's the basic idea.

**Comment by duerdak** [comment]
Perhaps this would be useful for structs such as SDL_Rect or SDL_Texture as well.

**Comment by icculus** [comment]
We'll definitely do that when we improve the wiki bridge's script, but right now the bridge only deals with functions.
