### ISSUE TITLE
Chore: add removal script to ci

### ISSUE THREAD

**Issue by Green-Sky** [libsdl-org/sdlwiki#550]
The auto removal script from https://github.com/libsdl-org/sdlwiki/pull/497 should be added to ci, and should be run weekly.

`SDL_GetRendererInfo` and `SDL_RendererInfo` where removed recently, maybe there is more...

**Comment by Green-Sky** [comment]
How? If the script generates a difference, it should create (or update) a pr automatically.

**Comment by icculus** [comment]
So I don't want to add this to CI, since once SDL3 is locked down, we should _never_ remove a symbol (until SDL4, at least).

Also, the script will only catch symbols that have been renamed from SDL2; it won't catch things that were completely removed, and it won't catch symbols we added and then changed/removed during SDL3 development.

Case in point: It didn't catch SDL_GetRendererInfo when I just tried it.

**Comment by Green-Sky** [comment]
Right, good points.
